question_data = [
    {"category": "Science: Computers",
     "type": "multiple", "difficulty": "medium",
     "question": "Nvidia&#039;s headquarters are based in which Silicon Valley city?",
     "correct_answer": "Santa Clara",
     "incorrect_answers": ["Palo Alto", "Cupertino", "Mountain View"]
     },
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Which of these names was an actual codename for a cancelled Microsoft project?",
     "correct_answer": "Neptune", "incorrect_answers": ["Enceladus", "Pollux", "Saturn"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "What port does HTTP run on?", "correct_answer": "80", "incorrect_answers": ["53", "443", "23"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
                                       "question": "In programming, the ternary operator is mostly defined with what symbol(s)?",
                                       "correct_answer": "?:", "incorrect_answers": ["??", "if then", "?"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Which data structure does FILO apply to?", "correct_answer": "Stack",
     "incorrect_answers": ["Queue", "Heap", "Tree"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Which of these is not a key value of Agile software development?",
     "correct_answer": "Comprehensive documentation",
     "incorrect_answers": ["Individuals and interactions", "Customer collaboration", "Responding to change"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Laserjet and inkjet printers are both examples of what type of printer?",
     "correct_answer": "Non-impact printer",
     "incorrect_answers": ["Impact printer", "Daisywheel printer", "Dot matrix printer"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "What was the name of the first Bulgarian personal computer?", "correct_answer": "IMKO-1",
     "incorrect_answers": ["Pravetz 82", "Pravetz 8D", "IZOT 1030"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following computer components can be built using only NAND gates?",
     "correct_answer": "ALU", "incorrect_answers": ["CPU", "RAM", "Register"]}]
